In [19]:
import numpy as np
import pandas as pd

# 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [34]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [37]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
a3 = a.reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [40]:
a4 = a.reshape(6,2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [41]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [43]:
b1 = a.reshape(2,-1) 
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
b2 = a.reshape(3,-1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
b3 = a.reshape(4,-1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [50]:
b4 = a.reshape(-1,2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [51]:
b5 = a.reshape(-1,1)
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [65]:
b5.shape

(12, 1)

С точки зерения Numpy - НЕТ :) 

In [66]:
# и для успокоения души :)
b4[3][1]

19

In [67]:
b5[3][0]

15

In [69]:
b5[3]

array([15])

# 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [117]:
mu, sigma = 0, 1.0 # mean and standard deviation
rm = np.random.normal(mu,sigma,size=(3,4))
abs(mu - np.mean(rm)) < 0.01

False

In [119]:
abs(sigma - np.std(rm, ddof=1)) < 0.01

False

Я так понял что в этом и была цель, что на таком маленьком массиве сложно создать добиться распредления с такими условиями и надо повышать размерность 

In [120]:
rm2 = np.random.normal(mu,sigma,size=(300,400))
abs(mu - np.mean(rm2)) < 0.01

True

In [121]:
abs(sigma - np.std(rm2, ddof=1)) < 0.01

True

In [112]:
rm2.size

120000

In [128]:
rm3 = rm2.reshape(1,-1) 
rm3.size

120000

# 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [132]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [136]:
b = np.arange(20,1,-2).reshape(1,-1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [147]:
type(a) == type(b)

True

In [149]:
a.size == b.size

True

In [146]:
a.shape == b.shape

False

Разная форма. Один одномерный, второй многомерный, но с одним измерением

# 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [156]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

d = np.concatenate((a, b), axis=0)
d

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [158]:
d.size

10

# 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [162]:
a = np.arange(0,12)
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [165]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [167]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [169]:
B.size

16

In [175]:
np.linalg.det(B)
#np.linalg.inv(B)

0.0

Определитель матрицы равен 0, значит матрица вырожденная и посчитать обратную нельзя

# 10
 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [177]:
np.random.seed(42)

# 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [180]:
c = np.random.randint(16,size=16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

In [182]:
c.shape

(16,)

Не уверен в том что, что понималось под равномерно распределным...

# 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [183]:
C = c.reshape(4,4)
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])

In [184]:
D = B + C*10
D

array([[125, 154, 123, 102],
       [134,  90, 146, 212],
       [ 43, 146, 249, 312],
       [102, 162, 242, 372]])

In [185]:
np.linalg.det(D)

-149097600.0

In [186]:
np.linalg.matrix_rank(D)

4

In [188]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.0004711 ,  0.0111539 , -0.00253901, -0.00435621],
       [ 0.00957225, -0.01715762, -0.00876527,  0.01450486],
       [-0.00167085,  0.01408514,  0.02130578, -0.02543824],
       [-0.00321078, -0.00474937, -0.0093469 ,  0.01411451]])

# 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [193]:
D_inv[np.where(D_inv < 0)] = 0
D_inv[np.where(D_inv > 0)] = 1
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [194]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [195]:
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])

In [199]:
E = np.zeros((4,4))
E[np.where(D_inv == 1)] = B[np.where(D_inv == 1)]
E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]
E

array([[  5.,  14.,  10.,   7.],
       [ 14.,   4.,   6., 122.],
       [  2.,  86., 149.,  10.],
       [  7.,   4.,   3., 302.]])